import { Vegan } from "lucide-react";

export interface Meal {
  id: string;
  name: string;
  price: number;
  ingredients: string[];
}

export interface Category {
  id: string;
  title: string;
  meals: Meal[];
}

export const categories: Category[] = [
  {
    id: "1",
    title: "Pizza 1",
    meals: [
      {
        id: "1",
        name: "MARGHERITA",
        price: 110,
        ingredients: ["Tomat", "Ost"],
      },
      {
        id: "2",
        name: "FUNGI",
        price: 110,
        ingredients: ["Färska champinjoner"],
      },
      {
        id: "3",
        name: "VESUVIO",
        price: 110,
        ingredients: ["Skinka"],
      },
      {
        id: "4",
        name: "MOZZARELLA",
        price: 110,
        ingredients: ["Mozzarellla"],
      },
      {
        id: "5",
        name: "DELL OPERA",
        price: 110,
        ingredients: ["Skinka", "Tonfisk"],
      },
      {
        id: "6",
        name: "CAPRICIOSA",
        price: 110,
        ingredients: ["Skinka", "Champinjoner"],
      },
      {
        id: "7",
        name: "BANAN PIZZA",
        price: 110,
        ingredients: ["Skinka", "Banan", "Curry"],
      },
      {
        id: "8",
        name: "HAWAII",
        price: 110,
        ingredients: ["Skinka", "Ananas"],
      },
      {
        id: "9",
        name: "BUSSOLA",
        price: 110,
        ingredients: ["Skinka", "Räkor"],
      },
      {
        id: "10",
        name: "NAPOLITANA",
        price: 110,
        ingredients: ["Sardeller", "Oliver"],
      },
      {
        id: "11",
        name: "BRUNO",
        price: 110,
        ingredients: ["Salami", "F. paprika", "Oliver", "Lök"],
      },
      {
        id: "12",
        name: "CALZONE (Inbakad)",
        price: 110,
        ingredients: ["Skinka"],
      },
      {
        id: "13",
        name: "LEONARDO",
        price: 110,
        ingredients: ["Tonfisk", "Räkor"],
      },
      {
        id: "14",
        name: "MARINARA",
        price: 110,
        ingredients: ["Räkor", "Musslor"],
      },
      {
        id: "15",
        name: "PEPPERONIPIZZA",
        price: 110,
        ingredients: ["Pepperonikorv"],
      },
    ],
  },

  {
    id: "2",
    title: "Pizza 2",
    meals: [
      {
        id: "16",
        name: "VEGETARIANA",
        price: 120,
        ingredients: [
          "Paprika",
          "Lök",
          "Oliver",
          "F.Champ",
          "F.Tomater",
          "Kronärtskocka",
        ],
      },
      {
        id: "17",
        name: "OLYMPIA",
        price: 120,
        ingredients: ["Skinka", "Räkor", "F.Champinjoner"],
      },
      {
        id: "18",
        name: "QUATTRO STAGIONI",
        price: 120,
        ingredients: [
          "Skinka",
          "Räkor",
          "Musslor",
          "Oliver",
          "Kronärtskocka",
          "F.Champ",
        ],
      },
      {
        id: "19",
        name: "KEBAB PIZZA",
        price: 120,
        ingredients: [
          "Kebabkött",
          "Tomat",
          "Pepperoni",
          "Lök",
          "Vitlökssås",
          "Stark sås",
        ],
      },
      {
        id: "20",
        name: "MAFIOSO",
        price: 120,
        ingredients: ["Salami", "Lök", "Feferoni", "F.Tomat", "Stark krydda"],
      },
      {
        id: "21",
        name: "PIZZA-PAZZA",
        price: 120,
        ingredients: ["Gorgonzola", "F.Champ", "Skinka"],
      },
      {
        id: "22",
        name: "FADOSO",
        price: 120,
        ingredients: ["Köttfärs", "Lök", "F.Tomater", "Fårost"],
      },
      {
        id: "23",
        name: "POMPEI",
        price: 120,
        ingredients: ["Salami", "Bacon", "Lök", "Ägg"],
      },
      {
        id: "24",
        name: "GRATINATE",
        price: 120,
        ingredients: [
          "Skinka",
          "Räkor",
          "Paprika",
          "Purjolök",
          "F.Champinjoner",
        ],
      },
      {
        id: "25",
        name: "TROPICANA",
        price: 120,
        ingredients: ["Skinka", "Banan", "Ananas", "Curry"],
      },
      {
        id: "26",
        name: "CACCIATORE",
        price: 120,
        ingredients: ["Salami", "Purjolök", "F.Champ"],
      },
      {
        id: "27",
        name: "TOSCANA",
        price: 120,
        ingredients: ["Mozzarella", "Kyckling", "Banan", "Jordnötter", "Curry"],
      },
      {
        id: "28",
        name: "ILYOS SPECIAL",
        price: 120,
        ingredients: [
          "Köttfärs",
          "F.Paprika",
          "F.Champ",
          "Lök",
          "Stark krydda",
        ],
      },
    ],
  },
  {
    id: "3",
    title: "Pizza 3",
    meals: [
      {
        id: "29",
        name: "DANIELA",
        price: 125,
        ingredients: [
          "Fårost",
          "F.Paprika",
          "Purjolök",
          "Pesto",
          "Ruccola",
          "F.Champ",
        ],
      },
      {
        id: "30",
        name: "ISABEL",
        price: 125,
        ingredients: ["Mozzarella", "Ruccola", "F.Tomater"],
      },
      {
        id: "31",
        name: "MICHELE",
        price: 125,
        ingredients: ["Fläskfilé", "Banan", "F.Champ", "Bearnaise"],
      },
      {
        id: "32",
        name: "SICILIA",
        price: 125,
        ingredients: [
          "Oxfilé",
          "F.Tomater",
          "F.Paprika",
          "Stark krydda",
          "Bearnaise",
        ],
      },
      {
        id: "33",
        name: "FANTASIA",
        price: 125,
        ingredients: ["Oxfilé", "F.Tomater", "F.Champinjojner", "Bearnaise"],
      },
      {
        id: "34",
        name: "LECHEF",
        price: 125,
        ingredients: [
          "Mozzarella",
          "Parmaskinka",
          "Oliver",
          "F.Tomater",
          "Ruccola",
        ],
      },
      {
        id: "35",
        name: "FRUTTI DI MARE",
        price: 125,
        ingredients: ["Räkor", "Musslor", "Tonfisk", "Krabba"],
      },
      {
        id: "36",
        name: "QUATTRO FORMAGGI",
        price: 125,
        ingredients: [
          "Mozzarella",
          "Gorgonzola",
          "Fårost",
          "Parmesan",
          "F.Tomater",
        ],
      },
      {
        id: "37",
        name: "SPECIALE",
        price: 125,
        ingredients: ["Skinka", "F.Champinjoner", "Räkor"],
      },
      {
        id: "38",
        name: "CALZONE SPECIAL",
        price: 125,
        ingredients: ["Skinka", "F.Champinjoner", "Räkor"],
      },
    ],
  },
  {
    id: "4",
    title: "Special Pizzor",
    meals: [
      {
        id: "39",
        name: "ANNA LIND SPECIAL",
        price: 130,
        ingredients: [
          "Rödlök",
          "Soltorkade tomater",
          "Kebab",
          "Isbergssallad",
          "Vitlök",
          "Stark sås",
        ],
      },
      {
        id: "40",
        name: "DELLE MANGIONE",
        price: 130,
        ingredients: [
          "Skinka",
          "Champinjoner",
          "Räkor",
          "Salami",
          "Gorgonzola",
        ],
      },
      {
        id: "41",
        name: "VÄSTERTORP SPECIAL",
        price: 130,
        ingredients: [
          "Pepperonikorv",
          "Lök",
          "Paprika",
          "Soltorkade tomater",
          "Ruccola",
        ],
      },
      {
        id: "42",
        name: "IL CARPACCIO",
        price: 130,
        ingredients: [
          "Mozzarella",
          "Parmesan",
          "Bresaola",
          "Pinjenötter",
          "Ruccola",
        ],
      },
      {
        id: "43",
        name: "VERONA",
        price: 130,
        ingredients: [
          "Mozzarella",
          "Parmaskinka",
          "Ruccola",
          "Soltorkade tomater",
          "Zucchini",
          "F.Champinjoner",
        ],
      },
      {
        id: "44",
        name: "SORRENTO",
        price: 130,
        ingredients: [
          "Mozzarella",
          "Parmaskinka",
          "Spenat",
          "Pinjenötter",
          "Ruccola",
          "F.Champinjoner",
        ],
      },
      {
        id: "45",
        name: "RIMINI",
        price: 130,
        ingredients: [
          "Mozzarella",
          "Salami",
          "Soltorkade tomater",
          "Ruccola",
          "Purjolök",
          "F.Champinjoner",
        ],
      },
      {
        id: "46",
        name: "NAPOLI",
        price: 130,
        ingredients: [
          "Mozzarella",
          "Bresaola",
          "Parmesan",
          "Ruccola",
          "Soltorkade tomater",
          "Färska champinjoner",
          "Zucchini",
        ],
      },
      {
        id: "47",
        name: "DELLA CASA",
        price: 130,
        ingredients: [
          "Mozzarella",
          "Aubergine",
          "Zucchini",
          "Parmesan",
          "Ruccola",
          "Soltorkade tomater",
          "Färska champinjoner",
        ],
      },
      {
        id: "48",
        name: "VENEZIA",
        price: 130,
        ingredients: [
          "Mozzarella",
          "Kyckling",
          "Tomater",
          "Spenat",
          "F.Champinjoner",
          "Curry",
          "Ruccola",
        ],
      },
      {
        id: "49",
        name: "KYCKLINGKEBAB PIZZA",
        price: 130,
        ingredients: [
          "Kycklingkebab",
          "Lök",
          "Tomat",
          "Feferoni",
          "Isbergssallad",
          "Vitlökssås",
          "Stark sås",
        ],
      },
      {
        id: "50",
        name: "COSTANTINO",
        price: 130,
        ingredients: [
          "Mozzarella",
          "Fläskfilé",
          "Spenat",
          "Soltorkade tomater",
          "Stark krydda",
          "Bearnaisesås",
        ],
      },
      {
        id: "51",
        name: "ARROSTO",
        price: 130,
        ingredients: [
          "Mozzarella",
          "Aubergine",
          "Soltorkade tomater",
          "F.Paprika",
          "Parmesan",
          "Stark krydda",
          "Ruccola",
        ],
      },
      {
        id: "52",
        name: "AL PACINO",
        price: 130,
        ingredients: [
          "Mozzarella",
          "Salami",
          "Zucchini",
          "Soltorkade tomater",
          "F.Paprika",
          "F.Champinjoner",
          "Stark krydda",
        ],
      },
      {
        id: "53",
        name: "DE NIRO",
        price: 130,
        ingredients: [
          "Mozzarella",
          "Köttfärs",
          "Spenat",
          "Soltorkade tomater",
          "Purjolök",
          "Ruccola",
        ],
      },
      {
        id: "54",
        name: "MEZZA LUNA",
        price: 130,
        ingredients: [
          "Mozzarella",
          "Parmaskinka",
          "Mozzarella",
          "Ruccola",
          "Havssalt",
          "Olivolja",
        ],
      },
      {
        id: "55",
        name: "RUCCOLA",
        price: 130,
        ingredients: ["Mozzarella", "Ruccola", "Havssalt", "Olivolja"],
      },
      {
        id: "56",
        name: "MELANZANE",
        price: 130,
        ingredients: [
          "Mozzarella",
          "F.Champinjoner",
          "F.Tomater",
          "Spenat",
          "Aubergine",
          "Ruccola",
          "Havssalt",
        ],
      },
      {
        id: "57",
        name: "CHICHKEN SPECIAL",
        price: 130,
        ingredients: [
          "Mozzarella",
          "Kyckling",
          "Rödlök",
          "F.Paprika",
          "Ruccola",
          "Pesto",
        ],
      },
      {
        id: "58",
        name: "DI MODENA",
        price: 130,
        ingredients: [
          "Marinerad scampi",
          "Balsamvinäger",
          "Olivolja",
          "Spenat",
          "Havssalt",
          "Citron",
          "F.Champinjoner",
        ],
      },
      {
        id: "59",
        name: "DEVRAN SPECIAL",
        price: 130,
        ingredients: [
          "Mozzarella",
          "Fläskfilé",
          "Kantareller",
          "Ruccola",
          "Bearnaisesås",
        ],
      },
      {
        id: "60",
        name: "CAPRESE",
        price: 130,
        ingredients: [
          "Fläskfilé",
          "Kantareller",
          "Soltorkade tomater",
          "Spenat",
          "Bearnaisesås",
        ],
      },
      {
        id: "61",
        name: "LEIF SPECIAL",
        price: 130,
        ingredients: [
          "Mozzarella",
          "Salami",
          "Parmaskinka",
          "Bresaolia",
          "Ruccola",
        ],
      },
      {
        id: "62",
        name: "MONIKA SPECIAL",
        price: 130,
        ingredients: ["Gorgonzola", "Fläskfile", "Kantareller", "Ruccola"],
      },
      {
        id: "63",
        name: "U-BÅT HALVINBAKAD",
        price: 130,
        ingredients: ["Oxfile", "F.Champinjoner", "Bearnaisesås", "Jalapeno"],
      },
      {
        id: "64",
        name: "VIKINGKEBAB",
        price: 130,
        ingredients: [
          "Kebab efter gräddning",
          "Isbergsallad",
          "Röd lök",
          "Tomater",
          "Pepperoni",
          "Stark vitlökssås",
        ],
      },
      {
        id: "65",
        name: "GOURMET",
        price: 130,
        ingredients: [
          "Oxfilé",
          "Tomat",
          "Lök",
          "Sparris",
          "Kronärtskocka",
          "Bearnaisesås",
        ],
      },
      {
        id: "66",
        name: "GYROS PIZZA",
        price: 130,
        ingredients: [
          "Gyros",
          "Isbergssallad",
          "Tomat",
          "Feferoni",
          "Lök",
          "Vitlök",
          "Stark sås",
        ],
      },
    ],
  },
  {
    id: "5",
    title: "Mexikanska Pizzor",
    meals: [
      {
        id: "67",
        name: "AZTEKA",
        price: 125,
        ingredients: [
          "Skinka",
          "Tacosås",
          "Tacokryddmix",
          "Jalapeno",
          "Gräddfil",
        ],
      },
      {
        id: "68",
        name: "ACAPULCO",
        price: 125,
        ingredients: [
          "Oxfilé",
          "Tacosås",
          "Tacokryddmix",
          "Lök",
          "Vitlök",
          "F.Champ.",
          "Jalapeno",
        ],
      },
      {
        id: "69",
        name: "MEXICANA",
        price: 125,
        ingredients: [
          "Köttfärs",
          "Tacosås",
          "Tacokryddmix",
          "Lök",
          "Vitlök",
          "Jalapeno",
        ],
      },
    ],
  },
  {
    id: "6",
    title: "Vegan Pizzor",
    meals: [
      {
        id: "70",
        name: "DELLA CASA VEGAN PIZZA",
        price: 140,
        ingredients: [
          "veganost",
          "aubergine",
          "zucchini",
          "ruccola",
          "soltorkade tomater",
          "f.champinjoner",
        ],
      },
      {
        id: "71",
        name: "ARROSTO VEGAN PIZZA",
        price: 140,
        ingredients: [
          "veganost",
          "aubergine",
          "soltorkade tomater",
          "f.paprika",
          "stark krydda",
          "ruccola",
        ],
      },
      {
        id: "72",
        name: "MELANZANE VEGAN PIZZA",
        price: 140,
        ingredients: [
          "veganost",
          "f.champinjoner",
          "f.tomater",
          "aubergine",
          "spenat",
          "ruccola",
          "havssalt",
        ],
      },
      {
        id: "73",
        name: "VEGETARISK VEGAN PIZZA",
        price: 140,
        ingredients: [
          "veganost",
          "paprika",
          "lök",
          "f.champinjoner",
          "oliver",
          "kronärtskocka",
        ],
      },
    ],
  },

  {
    id: "7",
    title: "Amerikanska Pan Pizzor",
    meals: [
      {
        id: "74",
        name: "HONULULU",
        price: 120,
        ingredients: [
          "Oxfilé",
          "Mozzarella",
          "F.Champinjoner",
          "Lök",
          "Tomater",
          "Bearnaise",
        ],
      },
      {
        id: "75",
        name: "MIAMI",
        price: 220,
        ingredients: ["Kyckling", "Mozzarella", "Banan", "Ananas", "Curry"],
      },
      {
        id: "76",
        name: "TEXAS",
        price: 220,
        ingredients: [
          "Feferoni",
          "Mozzarella",
          "F.Champinjoner",
          "Salami",
          "Lök",
          "Tomater",
        ],
      },
      {
        id: "77",
        name: "KANSAS",
        price: 220,
        ingredients: [
          "Skinka",
          "Mozzarella",
          "Salami",
          "Bacon",
          "Lök",
          "Tomater",
          "Paprika",
        ],
      },
      {
        id: "78",
        name: "LAS VEGAS",
        price: 220,
        ingredients: [
          "F.Champinjoner",
          "Mozzarella",
          "Feferoni",
          "Kyckling",
          "Oliver",
          "Tomater",
          "Lök",
        ],
      },
      {
        id: "79",
        name: "LOS ANGELES",
        price: 220,
        ingredients: [
          "Pepperonikorv",
          "Mozzarella",
          "Lök",
          "Paprika",
          "Oliver",
          "Tomat",
        ],
      },
    ],
  },

  {
    id: "8",
    title: "Sallader",
    meals: [
      {
        id: "80",
        name: "AVOCADO SALLAD",
        price: 120,
        ingredients: ["Skinka", "Räkor", "Avocado", "Majs", "Ägg", "Ost"],
      },
      {
        id: "81",
        name: "RAKSALLAD",
        price: 120,
        ingredients: [
          "Champinjoner",
          "Räkor",
          "Ägg",
          "Ananas",
          "Majs",
          "Ost",
          "Citron",
        ],
      },
      {
        id: "82",
        name: "KYCKLING SALLAD",
        price: 120,
        ingredients: ["Kyckling", "Ananas", "Majs", "Ost"],
      },
      {
        id: "83",
        name: "TONFISK SALLAD",
        price: 120,
        ingredients: ["Tonfisk", "Röd lök", "Majs", "Citron", "Ost", "Ägg"],
      },
      {
        id: "84",
        name: "SKALDJUR SALLAD",
        price: 120,
        ingredients: ["Musslor", "Räkor", "Majs", "Citron", "Ägg"],
      },
      {
        id: "85",
        name: "OST & SKINK SALLAD",
        price: 120,
        ingredients: ["Skinka", "Ost", "Ananas", "Majs", "Ägg"],
      },
      {
        id: "86",
        name: "GREKISK SALLAD",
        price: 120,
        ingredients: ["Fårost", "Röd lök", "Paprika", "Oliver", "Feferoni"],
      },
      {
        id: "87",
        name: "KEBAB SALLAD",
        price: 120,
        ingredients: ["Kebab", "Röd lök", "Feferoni", "Ost"],
      },
      {
        id: "88",
        name: "MATS SALLAD",
        price: 120,
        ingredients: [
          "Skinka",
          "Räkor",
          "Krabba",
          "Ananas",
          "Majs",
          "Ost",
          "Sparris",
        ],
      },
      {
        id: "89",
        name: "CEASAR SALLAD",
        price: 120,
        ingredients: [
          "Kyckling",
          "Röd lök",
          "Soltorkade tomater",
          "Paprika",
          "Majs",
          "Oliver",
          "Ruccola",
          "Feferoni",
        ],
      },
      {
        id: "90",
        name: "PARMA SALLAD",
        price: 120,
        ingredients: [
          "Parmaskinka",
          "Mozzarella",
          "Röd lök",
          "Paprika",
          "Soltorkade tomater",
          "Oliver",
          "Majs",
          "Ruccola",
          "Feferoni",
        ],
      },
    ],
  },

  {
    id: "9",
    title: "Pasta Rätter",
    meals: [
      {
        id: "91",
        name: "LASAGNE AL FORNO",
        price: 120,
        ingredients: ["Köttfärs", "Tomatsås", "Ost"],
      },
      {
        id: "92",
        name: "TORTIGLIONE A LA PAPALINA",
        price: 120,
        ingredients: ["Penne", "Oxfilé", "Purjolök", "Grädde"],
      },
      {
        id: "93",
        name: "SPAGHETTI CARBONARA",
        price: 120,
        ingredients: ["Bacon", "Ägg", "Grädde", "Parmesan", "Lök"],
      },
      {
        id: "94",
        name: "FRUTTI DI MARE",
        price: 120,
        ingredients: [
          "Spaghetti",
          "Räkor",
          "Musslor",
          "Scampi",
          "Vitlök",
          "Tomatsås",
          "Grädde",
        ],
      },
      {
        id: "95",
        name: "FETTUCINE AL POLLO",
        price: 120,
        ingredients: ["Penne", "Kyckling", "Pesto", "Gräddsås", "Broccoli"],
      },
      {
        id: "96",
        name: "SPAGHETTI BOLOGNESE",
        price: 120,
        ingredients: ["Köttfärs", "Tomatsås", "Parmesanost"],
      },
      {
        id: "97",
        name: "VEGETARISK",
        price: 120,
        ingredients: [
          "Penne",
          "Paprika",
          "Soltorkade tomater",
          "Zucchini",
          "Oliver",
          "Vitlök",
          "Purjolök",
          "Fetaost",
          "Tomat- och gräddsås",
        ],
      },
    ],
  },

  {
    id: "10",
    title: "Kebab Rätter",
    meals: [
      {
        id: "98",
        name: "KEBAB MED BRÖD (hembakat pitabröd)",
        price: 95,
        ingredients: [
          "Kebabkött",
          "Isbergssallad",
          "Tomat",
          "Feferoni",
          "Lök",
          "Stark- och vitlökssås",
        ],
      },
      {
        id: "99",
        name: "KEBABRULLE (tunnbröd)",
        price: 120,
        ingredients: [
          "Kebabkött",
          "Isbergssallad",
          "Tomat",
          "Feferoni",
          "Lök",
          "Stark- och vitlökssås",
        ],
      },
      {
        id: "100",
        name: "KEBABTALLRIK",
        price: 120,
        ingredients: [
          "Kebabkött",
          "Pommes",
          "Isbergssallad",
          "Tomat",
          "Feferoni",
          "Lök",
          "Stark- och vitlökssås",
        ],
      },
      {
        id: "101",
        name: "KEBAB ALEXANDER",
        price: 120,
        ingredients: [
          "Småskivat bröd",
          "Kebabkött",
          "Isbergssallad",
          "Tomat",
          "Feferoni",
          "Lök",
          "Stark- och vitlökssås",
        ],
      },
      {
        id: "102",
        name: "GYROSRULLE (tunnbröd)",
        price: 120,
        ingredients: [
          "Fläskkött",
          "Isbergssallad",
          "Tomat",
          "Feferoni",
          "Lök",
          "Stark- och vitlökssås",
        ],
      },
      {
        id: "103",
        name: "GYROSTALLRIK",
        price: 120,
        ingredients: [
          "Fläskkött",
          "Pommes",
          "Isbergssallad",
          "Tomat",
          "Feferoni",
          "Lök",
          "Stark- och vitlökssås",
        ],
      },
      {
        id: "104",
        name: "KYCKLINGRULLE (tunnbröd)",
        price: 120,
        ingredients: [
          "Kyckling",
          "Isbergssallad",
          "Tomat",
          "Feferoni",
          "Lök",
          "Stark- och vitlökssås",
        ],
      },
      {
        id: "105",
        name: "KYCKLINGTALLRIK",
        price: 120,
        ingredients: [
          "Kyckling",
          "Pommes",
          "Isbergssallad",
          "Tomat",
          "Feferoni",
          "Lök",
          "Stark- och vitlökssås",
        ],
      },
      {
        id: "106",
        name: "FALAFELRULLE (tunnbröd)",
        price: 120,
        ingredients: [
          "Falafel",
          "Isbergssallad",
          "Tomat",
          "Feferoni",
          "Lök",
          "Stark- och vitlökssås",
        ],
      },
      {
        id: "107",
        name: "FALAFELTALLRIK",
        price: 120,
        ingredients: [
          "Falafel",
          "Isbergssallad",
          "Tomat",
          "Feferoni",
          "Lök",
          "Stark- och vitlökssås",
        ],
      },
    ],
  },
  {
    id: "11",
    title: "Grillrätter",
    meals: [
      {
        id: "108",
        name: "GRILLAD KYCKLING",
        price: 140,
        ingredients: [
          "Fylld med mozzarella och parmaskinka.",
          "Frästa grönsaker.",
          "Pommes, ris eller klyftpotatis.",
        ],
      },
      {
        id: "109",
        name: "GRILLAD BIFF",
        price: 140,
        ingredients: ["Frästa grönsaker.", "Pommes, ris eller klyftpotatis."],
      },
      {
        id: "110",
        name: "LAXFILÉ",
        price: 140,
        ingredients: ["Frästa grönsaker.", "Pommes, ris eller klyftpotatis."],
      },
      {
        id: "111",
        name: "FLÄSKNOISETTE",
        price: 140,
        ingredients: ["Frästa grönsaker.", "Pommes, ris eller klyftpotatis."],
      },
      {
        id: "112",
        name: "HAMBURGARE 90g m pommes",
        price: 95,
        ingredients: ["Frästa grönsaker.", "Pommes, ris eller klyftpotatis."],
      },
      {
        id: "113",
        name: "HAMBURGARE 150g m pommes",
        price: 110,
        ingredients: ["Frästa grönsaker.", "Pommes, ris eller klyftpotatis."],
      },
    ],
  },
];
